language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3

env:
  - NETTE_VERSION="~2.0.0"
  - NETTE_VERSION="~2.1.0"
  - NETTE_VERSION="dev-master"

before_script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-dist
  - composer require --dev --no-interaction --prefer-dist nette/nette:${NETTE_VERSION}

script: ./vendor/bin/tester tests
